[package]
name = "tftp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
socket2.workspace = true

[dev-dependencies]
tempfile.workspace = true
